name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      node-version: '20'
      pnpm-version: '10'
      init-commands: |
        pnpm nx reset
        cd packages/generators/nest && pnpm exec tsc
        cd ../..
        cd packages/generators/react && pnpm exec tsc
        cd ../..
      parallel-commands-on-agents: |
        pnpm nx affected -t lint --parallel=4
      final-commands: |
        pnpm nx affected -t typecheck
        pnpm nx affected -t test --configuration=ci
        pnpm nx affected -t build

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.14.0
    secrets:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    with:
      number-of-agents: 3
      node-version: '20'
      pnpm-version: '10'
      install-commands: |
        pnpm install --frozen-lockfile
        cd packages/generators/nest && pnpm exec tsc
        cd ../..
        cd packages/generators/react && pnpm exec tsc
        cd ../..
